export const initialWordState = [
    { completed: false, definition: "", word: "", letter: "A" },
    { completed: false, definition: "", word: "", letter: "B" },
    { completed: false, definition: "", word: "", letter: "C" },
    { completed: false, definition: "", word: "", letter: "D" },
    { completed: false, definition: "", word: "", letter: "E" },
    { completed: false, definition: "", word: "", letter: "F" },
    { completed: false, definition: "", word: "", letter: "G" },
    { completed: false, definition: "", word: "", letter: "H" },
    { completed: false, definition: "", word: "", letter: "I" },
    { completed: false, definition: "", word: "", letter: "J" },
    { completed: false, definition: "", word: "", letter: "L" },
    { completed: false, definition: "", word: "", letter: "M" },
    { completed: false, definition: "", word: "", letter: "N" },
    { completed: false, definition: "", word: "", letter: "Ñ" },
    { completed: false, definition: "", word: "", letter: "O" },
    { completed: false, definition: "", word: "", letter: "P" },
    { completed: false, definition: "", word: "", letter: "Q" },
    { completed: false, definition: "", word: "", letter: "R" },
    { completed: false, definition: "", word: "", letter: "S" },
    { completed: false, definition: "", word: "", letter: "T" },
    { completed: false, definition: "", word: "", letter: "U" },
    { completed: false, definition: "", word: "", letter: "V" },
    { completed: false, definition: "", word: "", letter: "X" },
    { completed: false, definition: "", word: "", letter: "Y" },
    { completed: false, definition: "", word: "", letter: "Z" },
];