export const wordsList = {
    A: ["avion", "avaricia", "alinear", "aminoacido", "andamio"],
    B: ["babosa", "barbaro", "bocina", "blindar", "brillante"],
    C: ["camaleon", "cristal", "caramelo", "caminar", "cicatriz"],
    D: ["dialecto", "dardo", "dañino", "dermatitis", "deliberar"],
    E: ["ecografia", "enfretamiento", "enfriar", "eficaz", "enigma"],
    F: ["fiscal", "fiar", "forzar", "falico", "financiero"],
    G: ["galeno", "gemelo", "gancho", "genial", "genotipo"],
    H: ["ahijado", "habano", "habladuria", "horror", "hostil"],
    I: ["icono", "identidad", "idiota", "iglesia", "ignorante"],
    J: ["jabalina", "jeraca", "judaismo", "judicial", "jet"],
    L: ["llegar", "librar", "literario", "lentitud", "laberinto"],
    M: ["mito", "moderna", "matutina", "momia", "malcriar"],
    N: ["nafta", "nitido", "necio", "nebuloso", "nabo"],
    Ñ: ["alimaña", "piraña", "dueño", "paño", "amañar"],
    O: ["objetar", "obispado", "obeso", "obelisco", "obedecer"],
    P: ["palanca", "prevencion", "prestigio", "peyorativo", "perfumar"],
    Q: ["quisquilloso", "quieto", "quechua", "quincena", "quebrancho"],
    R: ["razonable", "remplazar", "restituir", "responsable", "raqueta"],
    S: ["salchicha", "salario", "sacaleches", "sacacorchos", "sabor"],
    T: ["trayectoria", "transpirar", "tijera", "tajante", "tierno"],
    U: ["ulcera", "urinario", "ultimar", "uniforme", "ufologia"],
    V: ["violonchelo", "vengar", "vacilacion", "vigente", "vacante"],
    X: ["axioma", "expropiar", "excavar", "excelente", "saxofon"],
    Y: ["yerba", "adyacente", "yacer", "yerno", "yugular"],
    Z: ["danzar", "cereza", "buzon", "cabizbajo", "zafar"],
};